kind: Deployment
apiVersion: apps/v1
metadata:
  name: apisix
  namespace: seda-redesign
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
    app.kubernetes.io/version: 2.10.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: apisix
      app.kubernetes.io/name: apisix
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: apisix
        app.kubernetes.io/name: apisix
    spec:
      volumes:
        - name: apisix-config
          configMap:
            name: apisix
            defaultMode: 420
      initContainers:
        - name: wait-etcd
          image: busybox:1.28
          command:
            - sh
            - "-c"
            - >-
              until nc -z apisix-etcd 2379; do echo
              waiting for etcd `date`; sleep 2; done;
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: apisix
          image: apache/apisix:3.7.0-debian
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
            - name: tls
              containerPort: 9443
              protocol: TCP
            - name: admin
              containerPort: 9180
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: apisix-config
              mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
          readinessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - "-c"
                  - sleep 30
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: apisix
  namespace: seda-redesign
data:
  config.yaml: >-
    deployment:
      role: traditional
      role_traditional:
        config_provider: etcd
      admin:
        admin_key:
          - name: admin
            key: edd1c9f034335f136f87ad84b625c8f1 # using fixed API token has security risk, please update it when you deploy to production environment
            role: admin
      etcd:
        host:
          - http://apisix-etcd:2379
        
        prefix: "/apisix"     # apisix configurations prefix
        timeout: 30   # 30 seconds
      plugins:                          # plugin list
        - api-breaker
        - authz-keycloak
        - basic-auth
        - batch-requests
        - consumer-restriction
        - cors
        - echo
        - fault-injection
        - grpc-transcode
        - hmac-auth
        - http-logger
        - ip-restriction
        - ua-restriction
        - jwt-auth
        - kafka-logger
        - key-auth
        - limit-conn
        - limit-count
        - limit-req
        - node-status
        - openid-connect
        - authz-casbin
        - prometheus
        - proxy-cache
        - proxy-mirror
        - proxy-rewrite
        - redirect
        - referer-restriction
        - request-id
        - request-validation
        - response-rewrite
        - serverless-post-function
        - serverless-pre-function
        - sls-logger
        - syslog
        - tcp-logger
        - udp-logger
        - uri-blocker
        - wolf-rbac
        - zipkin
        - server-info
        - traffic-split
        - gzip
        - real-ip
      stream_plugins:
        - mqtt-proxy
        - ip-restriction
        - limit-conn
      plugin_attr:
        server-info:
          report_interval: 60
          report_ttl: 3600
---
kind: Service
apiVersion: v1
metadata:
  name: apisix-admin
  namespace: seda-redesign
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
    app.kubernetes.io/version: 2.10.0
spec:
  ports:
    - name: apisix-admin
      protocol: TCP
      port: 9180
      targetPort: 9180
  selector:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: apisix-gateway
  namespace: seda-redesign
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
    app.kubernetes.io/version: 2.10.0
spec:
  ports:
    - name: apisix-gateway
      protocol: TCP
      port: 80
      targetPort: 9080
      nodePort: 31684
  selector:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
